// Emoji ve Sembol Okuma Sistemi
class EmojiReader {
  constructor() {
    // Emoji ve sembol sözlüğü - Türkçe karşılıkları
    this.emojiDictionary = {
      // Yüz ifadeleri
      '😊': 'gülümseyen yüz',
      '😃': 'gülen yüz',
      '😄': 'gözleri gülen mutlu yüz',
      '😁': 'kocaman gülen yüz',
      '😆': 'çok gülen yüz',
      '😅': 'terleyen gülen yüz',
      '😂': 'gözyaşlarıyla gülen yüz',
      '🤣': 'kahkaha atan yüz',
      '😉': 'göz kırpan yüz',
      '😌': 'rahatlamış yüz',
      '😍': 'kalp gözlü aşık yüz',
      '🥰': 'mutlu aşık yüz',
      '😘': 'öpücük gönderen yüz',
      '😗': 'öpücük yüzü',
      '😙': 'gözleri kapalı öpücük',
      '😚': 'utangaç öpücük',
      '🙂': 'hafif gülümseyen yüz',
      '🤗': 'sarılan yüz',
      '🤩': 'yıldızlı gözler',
      '🤔': 'düşünen yüz',
      '🤨': 'şüpheli yüz',
      '😐': 'ifadesiz yüz',
      '😑': 'donuk yüz',
      '😶': 'ağızsız yüz',
      '🙄': 'gözlerini deviren yüz',
      '😏': 'sırıtan yüz',
      '😣': 'zorlanmış yüz',
      '😥': 'endişeli yüz',
      '😮': 'şaşırmış yüz',
      '🤐': 'fermuar ağız',
      '😯': 'çok şaşırmış yüz',
      '😪': 'uykulu yüz',
      '😫': 'yorgun yüz',
      '😴': 'uyuyan yüz',
      '😵': 'sersem yüz',
      '🤯': 'aklı başından giden yüz',
      '🤠': 'kovboy şapkalı yüz',
      '🥳': 'parti yüzü',
      '😎': 'güneş gözlüklü havalı yüz',
      '🤓': 'inek gözlüklü yüz',
      '🧐': 'tek gözlüklü yüz',
      '😕': 'kafası karışmış yüz',
      '😟': 'endişeli yüz',
      '🙁': 'hafif üzgün yüz',
      '☹️': 'üzgün yüz',
      '😮': 'şaşkın yüz',
      '😯': 'çok şaşkın yüz',
      '😲': 'hayret yüzü',
      '😳': 'kızarmış yüz',
      '🥺': 'yalvaran gözler',
      '😦': 'kaşları çatık açık ağız',
      '😧': 'endişeli açık ağız',
      '😨': 'korkmuş yüz',
      '😰': 'endişeli terli yüz',
      '😥': 'üzgün ama rahatlamış',
      '😢': 'ağlayan yüz',
      '😭': 'hüngür hüngür ağlayan yüz',
      '😱': 'çığlık atan yüz',
      '😖': 'sıkıntılı yüz',
      '😣': 'azimli yüz',
      '😞': 'hayal kırıklığına uğramış',
      '😓': 'terli üzgün yüz',
      '😩': 'yorgun yüz',
      '😫': 'bitkin yüz',
      '🥱': 'esneyen yüz',
      '😤': 'zafer yüzü',
      '😡': 'kızgın yüz',
      '😠': 'sinirli yüz',
      '🤬': 'küfreden yüz',
      '😈': 'boynuzlu gülen şeytan',
      '👿': 'boynuzlu kızgın şeytan',
      '💀': 'kafatası',
      '☠️': 'kafatası ve kemikler',
      '💩': 'gülen kaka',
      '🤡': 'palyaço yüzü',
      '👹': 'japon canavarı',
      '👺': 'goblin',
      '👻': 'hayalet',
      '👽': 'uzaylı',
      '👾': 'uzaylı canavar',
      '🤖': 'robot yüzü',
      
      // El hareketleri
      '👋': 'el sallama',
      '🤚': 'kaldırılmış el arkası',
      '🖐️': 'açık el',
      '✋': 'kaldırılmış el',
      '🖖': 'vulkan selamı',
      '👌': 'tamam işareti',
      '🤏': 'az miktar',
      '✌️': 'zafer işareti',
      '🤞': 'şans dileme',
      '🤟': 'seni seviyorum işareti',
      '🤘': 'rock işareti',
      '🤙': 'ara beni',
      '👈': 'sola işaret',
      '👉': 'sağa işaret',
      '👆': 'yukarı işaret',
      '🖕': 'orta parmak',
      '👇': 'aşağı işaret',
      '☝️': 'yukarı işaret parmağı',
      '👍': 'beğeni',
      '👎': 'beğenmeme',
      '👊': 'yumruk',
      '✊': 'kaldırılmış yumruk',
      '🤛': 'sol yumruk',
      '🤜': 'sağ yumruk',
      '👏': 'alkış',
      '🙌': 'eller havada',
      '👐': 'açık eller',
      '🤲': 'dua eden eller',
      '🤝': 'el sıkışma',
      '🙏': 'dua eller',
      
      // Eğitim sembolleri
      '📚': 'kitaplar',
      '📖': 'açık kitap',
      '📝': 'not defteri',
      '✏️': 'kurşun kalem',
      '✒️': 'dolma kalem',
      '🖊️': 'tükenmez kalem',
      '🖍️': 'pastel boya',
      '📏': 'cetvel',
      '📐': 'üçgen cetvel',
      '✂️': 'makas',
      '📌': 'raptiye',
      '📍': 'harita iğnesi',
      '🎓': 'mezuniyet şapkası',
      '🏫': 'okul binası',
      '🎒': 'sırt çantası',
      '💻': 'dizüstü bilgisayar',
      '🖥️': 'masaüstü bilgisayar',
      '⌨️': 'klavye',
      '🖱️': 'fare',
      '💾': 'disket',
      '💿': 'CD',
      '📱': 'cep telefonu',
      
      // Matematik sembolleri
      '➕': 'artı işareti',
      '➖': 'eksi işareti',
      '✖️': 'çarpı işareti',
      '➗': 'bölme işareti',
      '🟰': 'eşittir işareti',
      '♾️': 'sonsuz',
      '💯': 'yüz puan',
      '🔢': 'sayılar',
      '🧮': 'abaküs',
      
      // Nesneler ve semboller
      '🚀': 'roket',
      '✈️': 'uçak',
      '🚁': 'helikopter',
      '🚂': 'tren',
      '🚗': 'araba',
      '🚌': 'otobüs',
      '🚲': 'bisiklet',
      '⛵': 'yelkenli',
      '🚤': 'sürat teknesi',
      '⚓': 'çapa',
      '🚦': 'trafik ışığı',
      '🚥': 'yatay trafik ışığı',
      '🗺️': 'harita',
      '🗿': 'moai heykeli',
      '🗽': 'özgürlük heykeli',
      '🗼': 'tokyo kulesi',
      '🏰': 'kale',
      '🏯': 'japon kalesi',
      '🏟️': 'stadyum',
      '🎡': 'dönme dolap',
      '🎢': 'lunapark treni',
      '🎠': 'atlıkarınca',
      '⛲': 'çeşme',
      '⛱️': 'plaj şemsiyesi',
      '🏖️': 'kumsal',
      '🏝️': 'ada',
      '🏜️': 'çöl',
      '🌋': 'volkan',
      '⛰️': 'dağ',
      '🏔️': 'karlı dağ',
      '🗻': 'fuji dağı',
      '🏕️': 'kamp',
      '🏠': 'ev',
      '🏡': 'bahçeli ev',
      '🏘️': 'evler',
      '🏚️': 'terk edilmiş ev',
      '🏗️': 'inşaat',
      '🏭': 'fabrika',
      '🏢': 'ofis binası',
      '🏬': 'alışveriş merkezi',
      '🏣': 'japon postanesi',
      '🏤': 'avrupa postanesi',
      '🏥': 'hastane',
      '🏦': 'banka',
      '🏨': 'otel',
      '🏩': 'aşk oteli',
      '🏪': 'market',
      '🏫': 'okul',
      '🏛️': 'antik bina',
      '⛪': 'kilise',
      '🕌': 'cami',
      '🕍': 'sinagog',
      '🕋': 'kabe',
      '⛩️': 'shinto tapınağı',
      
      // Doğa ve hayvanlar
      '🌞': 'güneş yüzü',
      '🌝': 'dolunay yüzü',
      '🌛': 'hilal ay yüzü',
      '🌜': 'son hilal ay yüzü',
      '🌚': 'yeni ay yüzü',
      '🌕': 'dolunay',
      '🌖': 'azalan dolunay',
      '🌗': 'son dördün',
      '🌘': 'azalan hilal',
      '🌑': 'yeni ay',
      '🌒': 'artan hilal',
      '🌓': 'ilk dördün',
      '🌔': 'artan dolunay',
      '🌙': 'hilal',
      '🌎': 'amerika kıtası',
      '🌍': 'avrupa afrika',
      '🌏': 'asya avustralya',
      '🪐': 'halkalı gezegen',
      '💫': 'baş döndüren yıldız',
      '⭐': 'yıldız',
      '🌟': 'parlayan yıldız',
      '✨': 'parıltılar',
      '⚡': 'şimşek',
      '☄️': 'kuyruklu yıldız',
      '💥': 'patlama',
      '🔥': 'ateş',
      '🌪️': 'kasırga',
      '🌈': 'gökkuşağı',
      '☀️': 'güneş',
      '🌤️': 'parçalı bulutlu güneş',
      '⛅': 'bulutlu güneş',
      '🌥️': 'bulutlu',
      '☁️': 'bulut',
      '🌦️': 'yağmurlu güneş',
      '🌧️': 'yağmur bulutu',
      '⛈️': 'fırtına',
      '🌩️': 'şimşekli bulut',
      '🌨️': 'kar bulutu',
      '❄️': 'kar tanesi',
      '☃️': 'kardan adam',
      '⛄': 'şapkasız kardan adam',
      '🌬️': 'rüzgar yüzü',
      '💨': 'hız',
      '🌊': 'dalga',
      '💧': 'su damlası',
      '💦': 'su sıçraması',
      '☔': 'yağmurlu şemsiye',
      '☂️': 'şemsiye',
      '🌂': 'kapalı şemsiye',
      '🌱': 'fide',
      '🌲': 'kozalaklı ağaç',
      '🌳': 'yaprak döken ağaç',
      '🌴': 'palmiye',
      '🌵': 'kaktüs',
      '🌾': 'pirinç sapı',
      '🌿': 'bitki',
      '☘️': 'yonca',
      '🍀': 'dört yapraklı yonca',
      '🍁': 'akçaağaç yaprağı',
      '🍂': 'düşen yapraklar',
      '🍃': 'rüzgarda yapraklar',
      '🌺': 'hibiscus',
      '🌻': 'ayçiçeği',
      '🌹': 'gül',
      '🥀': 'solmuş çiçek',
      '🌷': 'lale',
      '🌼': 'papatya',
      '🌸': 'kiraz çiçeği',
      '💐': 'buket',
      '🍄': 'mantar',
      '🌰': 'kestane',
      '🦀': 'yengeç',
      '🦞': 'ıstakoz',
      '🦐': 'karides',
      '🦑': 'kalamar',
      '🌍': 'dünya',
      '🌎': 'amerika',
      '🌏': 'asya',
      '🌐': 'meridyenli dünya',
      '🌑': 'yeni ay',
      '🌒': 'hilal',
      '🌓': 'ilk çeyrek ay',
      '🌔': 'şişkin ay',
      '🌕': 'dolunay',
      '🌖': 'azalan şişkin ay',
      '🌗': 'son çeyrek ay',
      '🌘': 'azalan hilal',
      '🌙': 'ay',
      '🌚': 'yeni ay yüzü',
      '🌛': 'ilk çeyrek ay yüzü',
      '🌜': 'son çeyrek ay yüzü',
      
      // Yiyecek ve içecekler
      '🍎': 'kırmızı elma',
      '🍏': 'yeşil elma',
      '🍐': 'armut',
      '🍊': 'portakal',
      '🍋': 'limon',
      '🍌': 'muz',
      '🍉': 'karpuz',
      '🍇': 'üzüm',
      '🍓': 'çilek',
      '🍈': 'kavun',
      '🍒': 'kiraz',
      '🍑': 'şeftali',
      '🥭': 'mango',
      '🍍': 'ananas',
      '🥥': 'hindistan cevizi',
      '🥝': 'kivi',
      '🍅': 'domates',
      '🍆': 'patlıcan',
      '🥑': 'avokado',
      '🥦': 'brokoli',
      '🥬': 'yeşil yapraklı sebze',
      '🥒': 'salatalık',
      '🌶️': 'acı biber',
      '🌽': 'mısır',
      '🥕': 'havuç',
      '🥔': 'patates',
      '🍠': 'tatlı patates',
      '🥐': 'kruvasan',
      '🥖': 'baget ekmek',
      '🥨': 'simit',
      '🧀': 'peynir',
      '🥚': 'yumurta',
      '🍳': 'sahanda yumurta',
      '🥓': 'domuz pastırması',
      '🥩': 'et',
      '🍗': 'tavuk butu',
      '🍖': 'kemikli et',
      '🌭': 'sosisli',
      '🍔': 'hamburger',
      '🍟': 'patates kızartması',
      '🍕': 'pizza',
      '🥪': 'sandviç',
      '🌮': 'taco',
      '🌯': 'burrito',
      '🥗': 'salata',
      '🥘': 'sığ tencere yemeği',
      '🍝': 'spagetti',
      '🍜': 'buhar çıkan kase',
      '🍲': 'yemek tenceresi',
      '🍛': 'köri',
      '🍣': 'suşi',
      '🍱': 'bento kutusu',
      '🍤': 'kızarmış karides',
      '🍙': 'pirinç topları',
      '🍚': 'pirinç',
      '🍘': 'pirinç krakeri',
      '🍥': 'balık keki',
      '🥮': 'ay keki',
      '🍢': 'oden',
      '🍡': 'dango',
      '🍧': 'buz',
      '🍨': 'dondurma',
      '🍦': 'külah dondurma',
      '🥧': 'turta',
      '🎂': 'doğum günü pastası',
      '🍰': 'pasta dilimi',
      '🧁': 'kek',
      '🍫': 'çikolata',
      '🍬': 'şeker',
      '🍭': 'lolipop',
      '🍮': 'muhallebi',
      '🍯': 'bal kavanozu',
      '🍼': 'biberon',
      '🥛': 'süt bardağı',
      '☕': 'kahve',
      '🍵': 'çay',
      '🍶': 'sake',
      '🍾': 'şampanya',
      '🍷': 'şarap',
      '🍸': 'kokteyl',
      '🍹': 'tropikal içecek',
      '🍺': 'bira',
      '🍻': 'bira bardakları',
      '🥂': 'kadeh tokuşturma',
      '🥃': 'viski bardağı',
      '🥤': 'pipetli bardak',
      '🧃': 'meyve suyu kutusu',
      '🧉': 'mate',
      '🧊': 'buz küpü',
      
      // Spor ve aktiviteler
      '⚽': 'futbol topu',
      '🏀': 'basketbol',
      '🏈': 'amerikan futbolu',
      '⚾': 'beyzbol',
      '🥎': 'softbol',
      '🎾': 'tenis',
      '🏐': 'voleybol',
      '🏉': 'rugby',
      '🥏': 'frizbi',
      '🎱': 'bilardo',
      '🪀': 'yo-yo',
      '🏓': 'masa tenisi',
      '🏸': 'badminton',
      '🏒': 'buz hokeyi',
      '🏑': 'çim hokeyi',
      '🥍': 'lakros',
      '🏏': 'kriket',
      '🪃': 'bumerang',
      '🥅': 'kale',
      '⛳': 'golf bayrağı',
      '🪁': 'uçurtma',
      '🏹': 'okçuluk',
      '🎣': 'olta',
      '🤿': 'dalış maskesi',
      '🥊': 'boks eldiveni',
      '🥋': 'dövüş sanatları üniforması',
      '🎽': 'koşu tişörtü',
      '🛹': 'kaykay',
      '🛷': 'kızak',
      '⛸️': 'buz pateni',
      '🥌': 'curling taşı',
      '🎿': 'kayak',
      '⛷️': 'kayakçı',
      '🏂': 'snowboard',
      '🪂': 'paraşüt',
      '🏋️': 'halterci',
      '🤼': 'güreşçiler',
      '🤸': 'jimnastikçi',
      '⛹️': 'basketbolcu',
      '🤺': 'eskrimci',
      '🤾': 'hentbolcu',
      '🏌️': 'golfçü',
      '🏇': 'at yarışı',
      '🧘': 'yoga pozisyonu',
      '🏄': 'sörfçü',
      '🏊': 'yüzücü',
      '🤽': 'su topu',
      '🚣': 'kürekçi',
      '🧗': 'tırmanıcı',
      '🚴': 'bisikletçi',
      '🚵': 'dağ bisikletçisi',
      '🎪': 'sirk çadırı',
      '🎭': 'tiyatro maskeleri',
      '🎨': 'sanatçı paleti',
      '🎬': 'klaketi',
      '🎤': 'mikrofon',
      '🎧': 'kulaklık',
      '🎼': 'müzik notası',
      '🎵': 'müzik notası',
      '🎶': 'müzik notaları',
      '🎹': 'piyano',
      '🥁': 'davul',
      '🎷': 'saksafon',
      '🎺': 'trompet',
      '🎸': 'gitar',
      '🪕': 'banjo',
      '🎻': 'keman',
      '🎲': 'zar',
      '♟️': 'satranç piyonu',
      '🎯': 'dart tahtası',
      '🎳': 'bowling',
      '🎮': 'oyun kumandası',
      '🎰': 'kumar makinesi',
      '🧩': 'yapboz parçası',
      
      // Seyahat ve yerler
      '🚗': 'araba',
      '🚕': 'taksi',
      '🚙': 'SUV',
      '🚌': 'otobüs',
      '🚎': 'troleybüs',
      '🏎️': 'yarış arabası',
      '🚓': 'polis arabası',
      '🚑': 'ambulans',
      '🚒': 'itfaiye',
      '🚐': 'minibüs',
      '🚚': 'kamyon',
      '🚛': 'TIR',
      '🚜': 'traktör',
      '🛴': 'scooter',
      '🚲': 'bisiklet',
      '🛵': 'motosiklet',
      '🏍️': 'yarış motosikleti',
      '🛺': 'otorikşa',
      '🚁': 'helikopter',
      '✈️': 'uçak',
      '🛫': 'kalkan uçak',
      '🛬': 'inen uçak',
      '🛩️': 'küçük uçak',
      '🚀': 'roket',
      '🛸': 'uçan daire',
      '🚤': 'sürat teknesi',
      '⛵': 'yelkenli',
      '🚣': 'kayık',
      '🛶': 'kano',
      '🚢': 'gemi',
      '⚓': 'çapa',
      '⛽': 'benzin pompası',
      '🚧': 'inşaat işareti',
      '🚦': 'trafik ışığı',
      '🚥': 'yatay trafik ışığı',
      '🚏': 'otobüs durağı',
      '🗺️': 'dünya haritası',
      '🗿': 'moai',
      '🗽': 'özgürlük heykeli',
      '🗼': 'tokyo kulesi',
      '🏰': 'avrupa kalesi',
      '🏯': 'japon kalesi',
      '🏟️': 'stadyum',
      '🎡': 'dönme dolap',
      '🎢': 'hız treni',
      '🎠': 'atlıkarınca',
      '⛲': 'fıskiye',
      '⛱️': 'plaj şemsiyesi',
      '🏖️': 'plaj',
      '🏝️': 'ıssız ada',
      '🏜️': 'çöl',
      '🌋': 'yanardağ',
      '⛰️': 'dağ',
      '🏔️': 'karlı dağ zirvesi',
      '🗻': 'fuji dağı',
      '🏕️': 'kamp alanı',
      '🏠': 'ev',
      '🏡': 'bahçeli ev',
      '🏘️': 'evler',
      '🏚️': 'terk edilmiş ev',
      '🏗️': 'inşaat alanı',
      '🏭': 'fabrika',
      '🏢': 'ofis binası',
      '🏬': 'mağaza',
      '🏣': 'japon postanesi',
      '🏤': 'avrupa postanesi',
      '🏥': 'hastane',
      '🏦': 'banka',
      '🏨': 'otel',
      '🏩': 'love hotel',
      '🏪': 'market',
      '🏫': 'okul',
      '🏛️': 'klasik bina',
      '⛪': 'kilise',
      '🕌': 'cami',
      '🕍': 'sinagog',
      '🛕': 'hindu tapınağı',
      '🕋': 'kabe',
      '⛩️': 'shinto kapısı',
      '🛤️': 'tren rayı',
      '🛣️': 'otoyol',
      '🗾': 'japonya haritası',
      '🎌': 'çapraz bayraklar',
      '🏞️': 'milli park',
      '🌅': 'gün doğumu',
      '🌄': 'dağlardan gün doğumu',
      '🌠': 'kayan yıldız',
      '🎇': 'havai fişek',
      '🎆': 'havai fişekler',
      '🌇': 'gün batımı',
      '🌆': 'alacakaranlık',
      '🏙️': 'şehir manzarası',
      '🌃': 'yıldızlı gece',
      '🌌': 'samanyolu',
      '🌉': 'gece köprüsü',
      '🌁': 'sisli',
      
      // Özel karakterler ve işaretler
      '❤️': 'kırmızı kalp',
      '🧡': 'turuncu kalp',
      '💛': 'sarı kalp',
      '💚': 'yeşil kalp',
      '💙': 'mavi kalp',
      '💜': 'mor kalp',
      '🖤': 'siyah kalp',
      '🤍': 'beyaz kalp',
      '🤎': 'kahverengi kalp',
      '💔': 'kırık kalp',
      '❣️': 'ünlem kalp',
      '💕': 'iki kalp',
      '💞': 'dönen kalpler',
      '💓': 'atan kalp',
      '💗': 'büyüyen kalp',
      '💖': 'parlayan kalp',
      '💘': 'oklu kalp',
      '💝': 'kurdeleli kalp',
      '💟': 'kalp süsü',
      '☮️': 'barış sembolü',
      '✝️': 'latin haçı',
      '☪️': 'hilal ve yıldız',
      '🕉️': 'om',
      '☸️': 'dharma çarkı',
      '✡️': 'davut yıldızı',
      '🔯': 'altı köşeli yıldız',
      '🕎': 'menora',
      '☯️': 'yin yang',
      '☦️': 'ortodoks haçı',
      '🛐': 'ibadet yeri',
      '⛎': 'yılancı',
      '♈': 'koç burcu',
      '♉': 'boğa burcu',
      '♊': 'ikizler burcu',
      '♋': 'yengeç burcu',
      '♌': 'aslan burcu',
      '♍': 'başak burcu',
      '♎': 'terazi burcu',
      '♏': 'akrep burcu',
      '♐': 'yay burcu',
      '♑': 'oğlak burcu',
      '♒': 'kova burcu',
      '♓': 'balık burcu',
      '🆔': 'kimlik',
      '⚛️': 'atom sembolü',
      '🉑': 'kabul edilebilir',
      '☢️': 'radyoaktif',
      '☣️': 'biyolojik tehlike',
      '📴': 'telefon kapalı',
      '📳': 'titreşim modu',
      '🈶': 'ücretli',
      '🈚': 'ücretsiz',
      '🈸': 'başvuru',
      '🈺': 'açık',
      '🈷️': 'aylık tutar',
      '✴️': 'sekiz köşeli yıldız',
      '🆚': 'karşı',
      '💮': 'beyaz çiçek',
      '🉐': 'pazarlık',
      '㊙️': 'gizli',
      '㊗️': 'tebrikler',
      '🈴': 'geçti',
      '🈵': 'dolu',
      '🈹': 'indirim',
      '🈲': 'yasak',
      '🅰️': 'A kan grubu',
      '🅱️': 'B kan grubu',
      '🆎': 'AB kan grubu',
      '🆑': 'temizle',
      '🅾️': '0 kan grubu',
      '🆘': 'SOS',
      '❌': 'çarpı işareti',
      '⭕': 'boş daire',
      '🛑': 'dur işareti',
      '⛔': 'giriş yok',
      '📛': 'isim etiketi',
      '🚫': 'yasak',
      '💯': 'yüz puan',
      '💢': 'kızgınlık sembolü',
      '♨️': 'kaplıca',
      '🚷': 'yaya girişi yasak',
      '🚯': 'çöp atmak yasak',
      '🚳': 'bisiklet yasak',
      '🚱': 'içme suyu değil',
      '🔞': 'on sekiz yaş üstü',
      '📵': 'cep telefonu yasak',
      '🚭': 'sigara içilmez',
      '❗': 'ünlem işareti',
      '❓': 'soru işareti',
      '❕': 'beyaz ünlem',
      '❔': 'beyaz soru işareti',
      '‼️': 'çift ünlem',
      '⁉️': 'ünlem soru',
      '🔅': 'düşük parlaklık',
      '🔆': 'yüksek parlaklık',
      '〽️': 'dalga işareti',
      '⚠️': 'uyarı',
      '🚸': 'çocuklar geçiyor',
      '🔱': 'üç dişli',
      '⚜️': 'zambak',
      '🔰': 'acemi şoför',
      '♻️': 'geri dönüşüm',
      '✅': 'onay işareti',
      '🈯': 'rezerve',
      '💹': 'yükselen grafik',
      '❇️': 'ışıltı',
      '✳️': 'sekiz köşeli yıldız',
      '❎': 'çarpı butonu',
      '🌐': 'dünya',
      '💠': 'elmas şekli',
      'Ⓜ️': 'metro',
      '🌀': 'siklon',
      '💤': 'uyku',
      '🏧': 'ATM',
      '🚾': 'WC',
      '♿': 'engelli erişimi',
      '🅿️': 'park',
      '🈳': 'boş',
      '🈂️': 'servis',
      '🛂': 'pasaport kontrolü',
      '🛃': 'gümrük',
      '🛄': 'bagaj teslim',
      '🛅': 'bagaj emanet',
      '🚹': 'erkek',
      '🚺': 'kadın',
      '🚼': 'bebek',
      '🚻': 'tuvalet',
      '🚮': 'çöp kutusu',
      '🎦': 'sinema',
      '📶': 'sinyal gücü',
      '🈁': 'burada',
      '🔣': 'semboller',
      '🔤': 'harfler',
      '🔡': 'küçük harfler',
      '🔠': 'büyük harfler',
      '🆖': 'iyi değil',
      '🆗': 'tamam',
      '🆙': 'yukarı',
      '🆒': 'havalı',
      '🆕': 'yeni',
      '🆓': 'bedava',
      '0️⃣': 'sıfır',
      '1️⃣': 'bir',
      '2️⃣': 'iki',
      '3️⃣': 'üç',
      '4️⃣': 'dört',
      '5️⃣': 'beş',
      '6️⃣': 'altı',
      '7️⃣': 'yedi',
      '8️⃣': 'sekiz',
      '9️⃣': 'dokuz',
      '🔟': 'on',
      '🔢': 'sayılar',
      '#️⃣': 'diyez',
      '*️⃣': 'yıldız tuşu',
      '⏏️': 'çıkar',
      '▶️': 'oynat',
      '⏸️': 'duraklat',
      '⏯️': 'oynat duraklat',
      '⏹️': 'durdur',
      '⏺️': 'kaydet',
      '⏭️': 'sonraki',
      '⏮️': 'önceki',
      '⏩': 'hızlı ileri',
      '⏪': 'hızlı geri',
      '⏫': 'hızlı yukarı',
      '⏬': 'hızlı aşağı',
      '◀️': 'geri',
      '🔼': 'yukarı',
      '🔽': 'aşağı',
      '➡️': 'sağ ok',
      '⬅️': 'sol ok',
      '⬆️': 'yukarı ok',
      '⬇️': 'aşağı ok',
      '↗️': 'sağ yukarı ok',
      '↘️': 'sağ aşağı ok',
      '↙️': 'sol aşağı ok',
      '↖️': 'sol yukarı ok',
      '↕️': 'yukarı aşağı ok',
      '↔️': 'sol sağ ok',
      '↪️': 'sol kıvrımlı sağ ok',
      '↩️': 'sağ kıvrımlı sol ok',
      '⤴️': 'yukarı kıvrımlı ok',
      '⤵️': 'aşağı kıvrımlı ok',
      '🔀': 'karıştır',
      '🔁': 'tekrarla',
      '🔂': 'bir kez tekrarla',
      '🔄': 'yenile',
      '🔃': 'dikey oklar',
      '🎵': 'nota',
      '🎶': 'notalar',
      '➕': 'artı',
      '➖': 'eksi',
      '➗': 'bölü',
      '✖️': 'çarpı',
      '♾️': 'sonsuz',
      '💲': 'dolar işareti',
      '💱': 'döviz',
      '™️': 'ticari marka',
      '©️': 'telif hakkı',
      '®️': 'tescilli',
      '〰️': 'dalgalı çizgi',
      '➰': 'kıvrımlı döngü',
      '➿': 'çift kıvrımlı döngü',
      '🔚': 'son',
      '🔙': 'geri',
      '🔛': 'açık',
      '🔝': 'en üst',
      '🔜': 'yakında',
      '✔️': 'onay işareti',
      '☑️': 'işaretli kutu',
      '🔘': 'radyo düğmesi',
      '🔴': 'kırmızı daire',
      '🟠': 'turuncu daire',
      '🟡': 'sarı daire',
      '🟢': 'yeşil daire',
      '🔵': 'mavi daire',
      '🟣': 'mor daire',
      '⚫': 'siyah daire',
      '⚪': 'beyaz daire',
      '🟤': 'kahverengi daire',
      '🔺': 'kırmızı üçgen yukarı',
      '🔻': 'kırmızı üçgen aşağı',
      '🔸': 'küçük turuncu elmas',
      '🔹': 'küçük mavi elmas',
      '🔶': 'büyük turuncu elmas',
      '🔷': 'büyük mavi elmas',
      '🔳': 'beyaz kare',
      '🔲': 'siyah kare',
      '▪️': 'küçük siyah kare',
      '▫️': 'küçük beyaz kare',
      '◾': 'orta siyah kare',
      '◽': 'orta beyaz kare',
      '◼️': 'büyük siyah kare',
      '◻️': 'büyük beyaz kare',
      '🟥': 'kırmızı kare',
      '🟧': 'turuncu kare',
      '🟨': 'sarı kare',
      '🟩': 'yeşil kare',
      '🟦': 'mavi kare',
      '🟪': 'mor kare',
      '🟫': 'kahverengi kare',
      '⬛': 'büyük siyah kare',
      '⬜': 'büyük beyaz kare',
      '🔈': 'hoparlör',
      '🔇': 'sessiz',
      '🔉': 'düşük ses',
      '🔊': 'yüksek ses',
      '🔔': 'zil',
      '🔕': 'zil kapalı',
      '📣': 'megafon',
      '📢': 'hoparlör',
      '👁️‍🗨️': 'konuşma balonu göz',
      '💬': 'konuşma balonu',
      '💭': 'düşünce balonu',
      '🗯️': 'öfke balonu',
      '♠️': 'maça',
      '♣️': 'sinek',
      '♥️': 'kupa',
      '♦️': 'karo',
      '🃏': 'joker',
      '🎴': 'çiçek kartı',
      '🀄': 'mahjong',
      '🕐': 'saat bir',
      '🕑': 'saat iki',
      '🕒': 'saat üç',
      '🕓': 'saat dört',
      '🕔': 'saat beş',
      '🕕': 'saat altı',
      '🕖': 'saat yedi',
      '🕗': 'saat sekiz',
      '🕘': 'saat dokuz',
      '🕙': 'saat on',
      '🕚': 'saat on bir',
      '🕛': 'saat on iki',
      '🕜': 'saat bir buçuk',
      '🕝': 'saat iki buçuk',
      '🕞': 'saat üç buçuk',
      '🕟': 'saat dört buçuk',
      '🕠': 'saat beş buçuk',
      '🕡': 'saat altı buçuk',
      '🕢': 'saat yedi buçuk',
      '🕣': 'saat sekiz buçuk',
      '🕤': 'saat dokuz buçuk',
      '🕥': 'saat on buçuk',
      '🕦': 'saat on bir buçuk',
      '🕧': 'saat on iki buçuk'
    };

    // Emoji pattern to match emojis
    this.emojiPattern = /[\u{1F600}-\u{1F64F}]|[\u{1F300}-\u{1F5FF}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{1F900}-\u{1F9FF}]|[\u{1F000}-\u{1F02F}]|[\u{1F0A0}-\u{1F0FF}]|[\u{1F100}-\u{1F64F}]|[\u{1F980}-\u{1F9FF}]|[\u{1FA70}-\u{1FAFF}]/gu;
  }

  // Metindeki emojileri Türkçe karşılıklarıyla değiştir
  convertEmojisToText(text) {
    if (!text) return text;
    
    // TÜM EMOJİLERİ KALDIR - Hiçbir emoji okunmasın
    let processedText = text.replace(this.emojiPattern, '');
    
    // Çoklu boşlukları temizle
    processedText = processedText.replace(/\s+/g, ' ').trim();
    
    return processedText;
  }

  // Emoji'nin Türkçe karşılığını al
  getEmojiMeaning(emoji) {
    return this.emojiDictionary[emoji] || 'bilinmeyen emoji';
  }

  // Metindeki tüm emojileri bul ve anlamlarını döndür
  findEmojisInText(text) {
    const emojis = text.match(this.emojiPattern) || [];
    const emojiMeanings = {};
    
    emojis.forEach(emoji => {
      if (!emojiMeanings[emoji]) {
        emojiMeanings[emoji] = this.getEmojiMeaning(emoji);
      }
    });
    
    return emojiMeanings;
  }

  // Eğitim amaçlı emoji açıklama metni oluştur
  createEducationalDescription(text) {
    const emojis = this.findEmojisInText(text);
    let description = '';
    
    if (Object.keys(emojis).length > 0) {
      description = 'Bu metinde kullanılan emojiler: ';
      Object.entries(emojis).forEach(([emoji, meaning]) => {
        description += `${emoji} (${meaning}), `;
      });
      description = description.slice(0, -2) + '.';
    }
    
    return description;
  }

  // Ses sentezi için metni optimize et
  optimizeForSpeech(text) {
    // Önce emojileri Türkçe karşılıklarıyla değiştir
    let optimizedText = this.convertEmojisToText(text);
    
    // Matematik ve özel semboller için özel durumlar
    optimizedText = optimizedText
      // Matematik sembolleri
      .replace(/\+/g, ' artı ')
      .replace(/\-(?=\d)/g, ' eksi ') // Sayıdan önce gelen eksi
      .replace(/\*/g, ' çarpı ')
      .replace(/\//g, ' bölü ')
      .replace(/=/g, ' eşittir ')
      .replace(/%/g, ' yüzde ')
      .replace(/</g, ' küçüktür ')
      .replace(/>/g, ' büyüktür ')
      
      // Para birimleri
      .replace(/\$/g, ' dolar ')
      .replace(/€/g, ' euro ')
      .replace(/£/g, ' sterlin ')
      .replace(/₺/g, ' türk lirası ')
      
      // Özel karakterler (sadece gerekli olanlar)
      .replace(/@/g, ' at ')
      .replace(/#/g, ' numara ')
      .replace(/&/g, ' ve ')
      
      // Parantezler (sadece açıklamada gerekirse)
      .replace(/\s*\(\s*/g, ', ')
      .replace(/\s*\)\s*/g, ', ')
      .replace(/\s*\[\s*/g, ', ')
      .replace(/\s*\]\s*/g, ', ')
      .replace(/\s*\{\s*/g, ', ')
      .replace(/\s*\}\s*/g, ', ')
      
      // Çoklu boşlukları ve virgülleri temizle
      .replace(/\s+/g, ' ')
      .replace(/,+/g, ',')
      .replace(/,\s*,/g, ',')
      .replace(/^\s*,\s*/g, '')
      .replace(/\s*,\s*$/g, '');
    
    // Noktalama işaretlerini temizle (cümle sonları hariç)
    // Nokta: Cümle ortasındaki noktaları kaldır, cümle sonundakileri koru
    optimizedText = optimizedText
      .replace(/\.(?!\s*$)(?!\s+[A-ZÇĞİÖŞÜ])/g, ' ') // Cümle ortasındaki noktalar
      .replace(/\.$/, ''); // Son noktayı da kaldır (ses sentezi otomatik duraklama yapar)
    
    // İki nokta üst üste ve noktalı virgül - genelde gereksiz
    optimizedText = optimizedText
      .replace(/:/g, ' ')
      .replace(/;/g, ', ');
    
    // Soru ve ünlem işaretlerini koru (tonlama için önemli)
    // Ama sadece cümle sonunda olmalı
    optimizedText = optimizedText
      .replace(/\?+/g, '?')
      .replace(/!+/g, '!')
      .replace(/\?\s*(?=[a-zçğıöşü])/g, '? ') // Soru işaretinden sonra büyük harf
      .replace(/!\s*(?=[a-zçğıöşü])/g, '! '); // Ünlem işaretinden sonra büyük harf
    
    // Kesme işareti ve tırnak işaretleri
    optimizedText = optimizedText
      .replace(/'/g, '')
      .replace(/"/g, '')
      .replace(/"/g, '')
      .replace(/"/g, '')
      .replace(/'/g, '')
      .replace(/'/g, '');
    
    // Çoklu boşlukları temizle
    optimizedText = optimizedText
      .replace(/\s+/g, ' ')
      .trim();
    
    return optimizedText;
  }

  // Matematik sembollerini ses sentezi için optimize et
  optimizeMathForSpeech(text) {
    return text
      .replace(/\^2/g, ' kare')
      .replace(/\^3/g, ' küp')
      .replace(/\^/g, ' üssü ')
      .replace(/√/g, ' karekök ')
      .replace(/∞/g, ' sonsuz ')
      .replace(/π/g, ' pi ')
      .replace(/∑/g, ' toplam ')
      .replace(/∏/g, ' çarpım ')
      .replace(/∫/g, ' integral ')
      .replace(/∂/g, ' kısmi türev ')
      .replace(/∇/g, ' nabla ')
      .replace(/∈/g, ' elemanıdır ')
      .replace(/∉/g, ' elemanı değildir ')
      .replace(/⊂/g, ' alt kümesidir ')
      .replace(/⊃/g, ' üst kümesidir ')
      .replace(/∪/g, ' birleşim ')
      .replace(/∩/g, ' kesişim ')
      .replace(/∅/g, ' boş küme ')
      .replace(/≠/g, ' eşit değildir ')
      .replace(/≈/g, ' yaklaşık eşittir ')
      .replace(/≤/g, ' küçük eşittir ')
      .replace(/≥/g, ' büyük eşittir ')
      .replace(/±/g, ' artı eksi ')
      .replace(/∓/g, ' eksi artı ');
  }

  // Öğrenci için emoji açıklaması oluştur
  createStudentFriendlyExplanation(emoji) {
    const meaning = this.getEmojiMeaning(emoji);
    const educationalContext = {
      '🚀': 'Roket uzaya giden bir araçtır. Çok hızlı gider ve astronotları uzaya taşır.',
      '😊': 'Bu mutlu bir yüz ifadesidir. Birisi mutlu olduğunda böyle gülümser.',
      '📚': 'Kitaplar bilgi hazinesidir. Okuyarak yeni şeyler öğreniriz.',
      '🧮': 'Abaküs eski bir hesaplama aletidir. Matematik öğrenirken kullanılır.',
      '🔬': 'Mikroskop çok küçük şeyleri büyüterek görmemizi sağlar. Fen derslerinde kullanılır.',
      '🌍': 'Dünyamız uzayda dönen mavi bir gezegendir. Üzerinde yaşadığımız yer.',
      '🌈': 'Gökkuşağı yağmurdan sonra güneş çıkınca oluşur. 7 rengi vardır.',
      '⭐': 'Yıldızlar geceleyin gökyüzünde parlayan gök cisimleridir.',
      '🎯': 'Hedef tahtası odaklanmayı ve başarıyı simgeler. Hedeflerimize ulaşmaya çalışırız.',
      '💡': 'Ampul fikirlerimizi ve buluşları simgeler. Yeni bir şey öğrendiğimizde ampul yanar!'
    };
    
    const baseExplanation = `${emoji} işareti "${meaning}" anlamına gelir.`;
    const contextualExplanation = educationalContext[emoji] || '';
    
    return contextualExplanation ? `${baseExplanation} ${contextualExplanation}` : baseExplanation;
  }
}

// Singleton instance
const emojiReader = new EmojiReader();
export default emojiReader;
